DECLARE

  CURSOR C_STATUS (P_STATUS_ID NUMBER) IS
    SELECT COUNT(1)
      FROM CARTORIO.STATUS
     WHERE STATUS_ID = P_STATUS_ID;

  N_COUNT NUMBER := 0;

BEGIN

  OPEN C_STATUS(-20223);
  FETCH C_STATUS INTO N_COUNT;
  CLOSE C_STATUS;

  IF N_COUNT <= 0 THEN
    INSERT INTO CARTORIO.STATUS(STATUS_ID, MESSAGE) VALUES (-20223, 'Código OTP inválido para o usuário.');
  ELSE
    UPDATE CARTORIO.STATUS SET MESSAGE = 'Código OTP inválido para o usuário.' WHERE STATUS_ID = -20223;
  END IF;

  OPEN C_STATUS(-20311);
  FETCH C_STATUS INTO N_COUNT;
  CLOSE C_STATUS;

  IF N_COUNT <= 0 THEN
    INSERT INTO CARTORIO.STATUS(STATUS_ID, MESSAGE) VALUES (-20311, 'Usuário não encontrado.');
  ELSE
    UPDATE CARTORIO.STATUS SET MESSAGE = 'Usuário não encontrado.' WHERE STATUS_ID = -20311;
  END IF;

  COMMIT;

END;